[package]
name = "single-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
ratatui.workspace = true
crossterm.workspace = true
serde_json.workspace = true
single-protocol = { path = "../single-protocol" }
