pub mod account;
pub mod config;
pub mod custom_agents;
pub mod lsp;
pub mod mcp;
pub mod paths;
pub mod permissions;
pub mod plugins;
pub mod profile;
pub mod project_context;
pub mod providers;
pub mod registry;
pub mod secrets;
pub mod skills;
pub mod tools;
pub mod worktree;

pub use config::{merge_layers, resolve, ConfigLayer, ResolvedConfig};
pub use paths::SingleDirs;
pub use registry::{builtin_registry, AgentDefinition};
